(function() {var implementors = {};
implementors["differential_dataflow"] = [{text:"impl&lt;R1:&nbsp;<a class=\"trait\" href=\"differential_dataflow/difference/trait.Diff.html\" title=\"trait differential_dataflow::difference::Diff\">Diff</a>, R2:&nbsp;<a class=\"trait\" href=\"differential_dataflow/difference/trait.Diff.html\" title=\"trait differential_dataflow::difference::Diff\">Diff</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Add.html\" title=\"trait core::ops::arith::Add\">Add</a>&lt;<a class=\"struct\" href=\"differential_dataflow/difference/struct.DiffPair.html\" title=\"struct differential_dataflow::difference::DiffPair\">DiffPair</a>&lt;R1, R2&gt;&gt; for <a class=\"struct\" href=\"differential_dataflow/difference/struct.DiffPair.html\" title=\"struct differential_dataflow::difference::DiffPair\">DiffPair</a>&lt;R1, R2&gt;",synthetic:false,types:["differential_dataflow::difference::DiffPair"]},];
implementors["time"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Add.html\" title=\"trait core::ops::arith::Add\">Add</a> for <a class=\"struct\" href=\"time/struct.Duration.html\" title=\"struct time::Duration\">Duration</a>",synthetic:false,types:["time::duration::Duration"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Add.html\" title=\"trait core::ops::arith::Add\">Add</a>&lt;<a class=\"struct\" href=\"time/struct.Duration.html\" title=\"struct time::Duration\">Duration</a>&gt; for <a class=\"struct\" href=\"time/struct.Timespec.html\" title=\"struct time::Timespec\">Timespec</a>",synthetic:false,types:["time::Timespec"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Add.html\" title=\"trait core::ops::arith::Add\">Add</a>&lt;<a class=\"struct\" href=\"time/struct.Duration.html\" title=\"struct time::Duration\">Duration</a>&gt; for <a class=\"struct\" href=\"time/struct.SteadyTime.html\" title=\"struct time::SteadyTime\">SteadyTime</a>",synthetic:false,types:["time::SteadyTime"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Add.html\" title=\"trait core::ops::arith::Add\">Add</a>&lt;<a class=\"struct\" href=\"time/struct.Duration.html\" title=\"struct time::Duration\">Duration</a>&gt; for <a class=\"struct\" href=\"time/struct.Tm.html\" title=\"struct time::Tm\">Tm</a>",synthetic:false,types:["time::Tm"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
